### ISSUE TITLE
Scanlines Dont Work

### ISSUE THREAD

**Issue by amoore2600** [MrX-8B/MiSTer-Arcade-AtariTetris#2]
I was unable to set scan lines using Scandoubler Fx from the menu.

**Comment by MrX-8B** [comment]
Thank you for your report.

In fact, some cores made by others do not have the scanline working.
Should I remove it from the menu if it doesn't work?

**Comment by amoore2600** [comment]
seems like it might be a good idea to remove it if it does not work.

**Comment by MrX-8B** [comment]
Ok. Let it work (although I don't know how yet), or enable only HQ2x.

**Comment by MrX-8B** [comment]
It will be fixed in the next release.
(It is already fixed in the experimental release.)

**Comment by amoore2600** [comment]
Confirmed fixed!!!
