### ISSUE TITLE
Implement a better way to handle 4-way

### ISSUE THREAD

**Issue by eniva** [MrX-8B/MiSTer-Arcade-AtariTetris#3]
Hello, MrX!

I've recently implemented a better way to handle 4-way-only games for the arcade cores on MiSTer.

Here's the github repo that documents how you can implement it in your core: https://github.com/eniva/fpga-controls

The README should give you an idea how it's handled! 😄 

I recommend adding the repo as a submodule for this repo so it can pull any latest changes, be it ever necessary.

**Comment by MrX-8B** [comment]
Thanks for the suggestion.
I'll try it out, check the play feel, and adopt it if it's good.

**Comment by klaritan** [comment]
Thanks! MAME uses Change Direction, other options are for users. (Stay Direction is mostly for Korean stick users). Stop is for Tetris players who do not want to risk anything.

I suggest trying Change Direction for general purposes!

**Comment by eniva** [comment]
If you don't like providing options, you can just force MODE_PREDICTION on the m_mode and skip implementing status bit entirely.

**Comment by MrX-8B** [comment]
Implemented and released features.
